apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: alert-emailer
      group_by: ['alertname']               #['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 5m
      routes:
        - receiver: slack_demo
          match:
            severity: slack
          group_wait: 10s
          repeat_interval: 1m
        - receiver: alert-emailer
          match:
            severity: slack
          group_wait: 10s
          repeat_interval: 1m
 
    receivers:
    - name: alert-emailer
      email_configs:
      - to: iti.project.2020@gmail.com
        #send_resolved: false
        from: iti.project.2020@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: "iti.project.2020@gmail.com"
        auth_identity: "iti.project.2020@gmail.com"
        auth_password: "@itisa40"
        require_tls: false
    - name: slack_demo
      slack_configs:
      - api_url: https://hooks.slack.com/services/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
        channel: '#project'
