apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: slack_api
      group_by: ['alertname', 'priority']
      match:
        severity: slack
      group_wait: 10s
      repeat_interval: 1m
 
    receivers:
    - name: slack_api
      slack_configs:
      - api_url: curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' https://hooks.slack.com/services/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
        channel: '#project'
