#======================================= Define Secret ======================================
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
data:
  username: d29yZHByZXNzX3VzZXI= 
  password: MTIzNDU2
  dbname: d29yZHByZXNzX2Ri
